package com.example.zhoutiandemo.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.zhoutiandemo.db.ShuJuKuDemo;

import com.example.zhoutiandemo.dao.ShuJuKuDemoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shuJuKuDemoDaoConfig;

    private final ShuJuKuDemoDao shuJuKuDemoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shuJuKuDemoDaoConfig = daoConfigMap.get(ShuJuKuDemoDao.class).clone();
        shuJuKuDemoDaoConfig.initIdentityScope(type);

        shuJuKuDemoDao = new ShuJuKuDemoDao(shuJuKuDemoDaoConfig, this);

        registerDao(ShuJuKuDemo.class, shuJuKuDemoDao);
    }
    
    public void clear() {
        shuJuKuDemoDaoConfig.clearIdentityScope();
    }

    public ShuJuKuDemoDao getShuJuKuDemoDao() {
        return shuJuKuDemoDao;
    }

}
