package com.rongbao.jyjy.rongbao.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.rongbao.jyjy.rongbao.bean.MyDB_Login_Bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MY_DB__LOGIN__BEAN".
*/
public class MyDB_Login_BeanDao extends AbstractDao<MyDB_Login_Bean, Long> {

    public static final String TABLENAME = "MY_DB__LOGIN__BEAN";

    /**
     * Properties of entity MyDB_Login_Bean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Username = new Property(1, String.class, "username", false, "USERNAME");
        public final static Property Image = new Property(2, int.class, "image", false, "IMAGE");
        public final static Property Userpsd = new Property(3, String.class, "userpsd", false, "USERPSD");
    }


    public MyDB_Login_BeanDao(DaoConfig config) {
        super(config);
    }
    
    public MyDB_Login_BeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MY_DB__LOGIN__BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY UNIQUE ," + // 0: id
                "\"USERNAME\" TEXT," + // 1: username
                "\"IMAGE\" INTEGER NOT NULL ," + // 2: image
                "\"USERPSD\" TEXT);"); // 3: userpsd
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MY_DB__LOGIN__BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MyDB_Login_Bean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(2, username);
        }
        stmt.bindLong(3, entity.getImage());
 
        String userpsd = entity.getUserpsd();
        if (userpsd != null) {
            stmt.bindString(4, userpsd);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MyDB_Login_Bean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String username = entity.getUsername();
        if (username != null) {
            stmt.bindString(2, username);
        }
        stmt.bindLong(3, entity.getImage());
 
        String userpsd = entity.getUserpsd();
        if (userpsd != null) {
            stmt.bindString(4, userpsd);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public MyDB_Login_Bean readEntity(Cursor cursor, int offset) {
        MyDB_Login_Bean entity = new MyDB_Login_Bean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // username
            cursor.getInt(offset + 2), // image
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // userpsd
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MyDB_Login_Bean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUsername(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImage(cursor.getInt(offset + 2));
        entity.setUserpsd(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(MyDB_Login_Bean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(MyDB_Login_Bean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MyDB_Login_Bean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
